<?php

return [
    'middleware' => [
        'default' => env('PLAYGROUND_MATRIX_API_MIDDLEWARE_DEFAULT', ['web']),
        'auth' => env('PLAYGROUND_MATRIX_API_MIDDLEWARE_AUTH', ['web', 'auth']),
        'guest' => env('PLAYGROUND_MATRIX_API_MIDDLEWARE_GUEST', ['web']),
    ],
    'policies' => [
        Playground\Matrix\Models\Backlog::class => Playground\Matrix\Api\Policies\BacklogPolicy::class,
        Playground\Matrix\Models\Board::class => Playground\Matrix\Api\Policies\BoardPolicy::class,
        Playground\Matrix\Models\Epic::class => Playground\Matrix\Api\Policies\EpicPolicy::class,
        Playground\Matrix\Models\Flow::class => Playground\Matrix\Api\Policies\FlowPolicy::class,
        Playground\Matrix\Models\Milestone::class => Playground\Matrix\Api\Policies\MilestonePolicy::class,
        Playground\Matrix\Models\Note::class => Playground\Matrix\Api\Policies\NotePolicy::class,
        Playground\Matrix\Models\Project::class => Playground\Matrix\Api\Policies\ProjectPolicy::class,
        Playground\Matrix\Models\Release::class => Playground\Matrix\Api\Policies\ReleasePolicy::class,
        Playground\Matrix\Models\Roadmap::class => Playground\Matrix\Api\Policies\RoadmapPolicy::class,
        Playground\Matrix\Models\Source::class => Playground\Matrix\Api\Policies\SourcePolicy::class,
        Playground\Matrix\Models\Sprint::class => Playground\Matrix\Api\Policies\SprintPolicy::class,
        Playground\Matrix\Models\Tag::class => Playground\Matrix\Api\Policies\TagPolicy::class,
        Playground\Matrix\Models\Team::class => Playground\Matrix\Api\Policies\TeamPolicy::class,
        Playground\Matrix\Models\Ticket::class => Playground\Matrix\Api\Policies\TicketPolicy::class,
        Playground\Matrix\Models\Version::class => Playground\Matrix\Api\Policies\VersionPolicy::class,
    ],
    'load' => [
        'policies' => (bool) env('PLAYGROUND_MATRIX_API_LOAD_POLICIES', true),
        'routes' => (bool) env('PLAYGROUND_MATRIX_API_LOAD_ROUTES', true),
    ],
    'routes' => [
        'backlogs' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_BACKLOGS', true),
        'boards' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_BOARDS', true),
        'epics' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_EPICS', true),
        'flows' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_FLOWS', true),
        'milestones' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_MILESTONES', true),
        'notes' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_NOTES', true),
        'projects' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_PROJECTS', true),
        'releases' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_RELEASES', true),
        'roadmaps' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_ROADMAPS', true),
        'sources' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_SOURCES', true),
        'sprints' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_SPRINTS', true),
        'tags' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_TAGS', true),
        'teams' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_TEAMS', true),
        'tickets' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_TICKETS', true),
        'versions' => (bool) env('PLAYGROUND_MATRIX_API_ROUTES_VERSIONS', true),
    ],

    'abilities' => [
        'admin' => [
            'playground-matrix-api:*',
        ],
        'manager' => [
            'playground-matrix-api:backlog:*',
            'playground-matrix-api:board:*',
            'playground-matrix-api:epic:*',
            'playground-matrix-api:flow:*',
            'playground-matrix-api:milestone:*',
            'playground-matrix-api:note:*',
            'playground-matrix-api:project:*',
            'playground-matrix-api:release:*',
            'playground-matrix-api:roadmap:*',
            'playground-matrix-api:source:*',
            'playground-matrix-api:sprint:*',
            'playground-matrix-api:tag:*',
            'playground-matrix-api:team:*',
            'playground-matrix-api:ticket:*',
            'playground-matrix-api:version:*',
        ],
        'user' => [
            'playground-matrix-api:backlog:view',
            'playground-matrix-api:backlog:viewAny',
            'playground-matrix-api:board:view',
            'playground-matrix-api:board:viewAny',
            'playground-matrix-api:epic:view',
            'playground-matrix-api:epic:viewAny',
            'playground-matrix-api:flow:view',
            'playground-matrix-api:flow:viewAny',
            'playground-matrix-api:milestone:view',
            'playground-matrix-api:milestone:viewAny',
            'playground-matrix-api:note:view',
            'playground-matrix-api:note:viewAny',
            'playground-matrix-api:project:view',
            'playground-matrix-api:project:viewAny',
            'playground-matrix-api:release:view',
            'playground-matrix-api:release:viewAny',
            'playground-matrix-api:roadmap:view',
            'playground-matrix-api:roadmap:viewAny',
            'playground-matrix-api:source:view',
            'playground-matrix-api:source:viewAny',
            'playground-matrix-api:sprint:view',
            'playground-matrix-api:sprint:viewAny',
            'playground-matrix-api:tag:view',
            'playground-matrix-api:tag:viewAny',
            'playground-matrix-api:team:view',
            'playground-matrix-api:team:viewAny',
            'playground-matrix-api:ticket:view',
            'playground-matrix-api:ticket:viewAny',
            'playground-matrix-api:ticket:create',
            'playground-matrix-api:ticket:edit',
            'playground-matrix-api:ticket:store',
            'playground-matrix-api:ticket:update',
            'playground-matrix-api:version:view',
            'playground-matrix-api:version:viewAny',
        ],
        // 'guest' => [
        //     'deny',
        // ],
        // 'guest' => [
        //     'app:view',

        //     'playground:view',

        //     'playground-auth:logout',
        //     'playground-auth:reset-password',

        //     'playground-matrix-api:backlog:view',
        //     'playground-matrix-api:backlog:viewAny',
        //     'playground-matrix-api:board:view',
        //     'playground-matrix-api:board:viewAny',
        //     'playground-matrix-api:epic:view',
        //     'playground-matrix-api:epic:viewAny',
        //     'playground-matrix-api:flow:view',
        //     'playground-matrix-api:flow:viewAny',
        //     'playground-matrix-api:milestone:view',
        //     'playground-matrix-api:milestone:viewAny',
        //     'playground-matrix-api:note:view',
        //     'playground-matrix-api:note:viewAny',
        //     'playground-matrix-api:project:view',
        //     'playground-matrix-api:project:viewAny',
        //     'playground-matrix-api:release:view',
        //     'playground-matrix-api:release:viewAny',
        //     'playground-matrix-api:roadmap:view',
        //     'playground-matrix-api:roadmap:viewAny',
        //     'playground-matrix-api:source:view',
        //     'playground-matrix-api:source:viewAny',
        //     'playground-matrix-api:sprint:view',
        //     'playground-matrix-api:sprint:viewAny',
        //     'playground-matrix-api:tag:view',
        //     'playground-matrix-api:tag:viewAny',
        //     'playground-matrix-api:team:view',
        //     'playground-matrix-api:team:viewAny',
        //     'playground-matrix-api:ticket:view',
        //     'playground-matrix-api:ticket:viewAny',
        //     'playground-matrix-api:version:view',
        //     'playground-matrix-api:version:viewAny',
        // ],
    ],
];
